users/urls.py
"""Defines url patterns for users."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

walk_in_clinic/urls.py
"""Defines url patterns for walk-in-clinic"""

from django.urls import path

from . import views

app_name = 'walk_in_clinic'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all appointments
    path('appointments/', views.appointments, name='appointments'),
    # Page that shows all appointments for dr
    path('appointments_dr/', views.appointments_dr, name='appointments_dr'),
    # Detail page for single appointments
    path('appointments/<int:appointment_id>/', views.appointment, name='appointment'),
    # Page for the dr to see a single appointment
    path('appointments_dr/<int:appointment_id>/', views.appointment_dr, name='appointment_dr'),
    # Page for adding new appointment
    path('new_appointment/', views.new_appointment, name='new_appointment'),
    # Page for editing appointments
    path('edit_appointment/<int:appointment_id>/', views.edit_appointment, name="edit_appointment"),
    # Page for seeing all clinics
    path('clinics/', views.clinics, name='clinics'),
    # Page for dr to see all of their clinics
    path('clinics_dr/', views.clinics_dr, name='clinics_dr'),
    # Page for seeing a single clinic
    path('clinics/<int:clinic_id>/', views.clinic, name='clinic'),
    # Page for dr to make a clinic
    path('new_clinic/', views.new_clinic, name='new_clinic'),
    # Page for dr to edit clinic
    path('edit_clinic/<int:clinic_id>/', views.edit_clinic, name='edit_clinic')
]

walk_in_clinic/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
import datetime
from django.utils import timezone, dateformat



class Appointment(models.Model):
    """A appointment the user creates"""
    names = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.CharField(max_length=200)
    notes = models.CharField(max_length=200, default="No notes at this time")
    clinic = models.ForeignKey('Clinic', on_delete=models.CASCADE, blank=True)
    start_time = models.DateTimeField(default=dateformat.format(timezone.now(), 'Y-m-d H:i:s'))
    end_time = models.DateTimeField(default=dateformat.format(timezone.now(), 'Y-m-d H:i:s'))

    def check_overlap(self, fixed_start, fixed_end, new_start, new_end):
        overlap = False
        if new_start == fixed_end or new_end == fixed_start:    #edge case
            overlap = False
        elif (new_start >= fixed_start and new_start <= fixed_end) or (new_end >= fixed_start and new_end <= fixed_end): #innner limits
            overlap = True
        elif new_start <= fixed_start and new_end >= fixed_end: #outter limits
            overlap = True
 
        return overlap
    
    def clean(self):
        if self.end_time <= self.start_time:
            raise ValidationError('Ending times must after starting times')
 
        appointments = Appointment.objects.filter(start_time=self.start_time)
        if appointments.exists():
            for appointment in appointments:
                if appointment.clinic == self.clinic:
                    if self.check_overlap(appointment.start_time, appointment.end_time, self.start_time, self.end_time):
                        raise ValidationError(
                            'There is an overlap with another appointment: ' + str(
                                appointment.start_time) + ' ' + str(appointment.end_time))

    def __str__(self):
        return self.service

class Clinic(models.Model):
    """A clinic can be set up by Doctor"""
    clinic_name = models.CharField(max_length=50, default=" ")
    location = models.CharField(max_length=50, default="39 York Road, London, SW81 4AQ, England")
    dr_name = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    dr_email = models.EmailField(max_length=50, default="Dan@gmail.com")
    dr_phonenumber = models.IntegerField(default=5263648574)
    payment_methods = [
        ('pp', 'PayPal'),
        ('cc', 'Credit Card'),
        ('dc', 'Debit Card'),
        ('ca', 'Cash')
    ]
    payment_method_available = models.CharField(max_length=2,choices=payment_methods,default=payment_methods[1])

    def __str__(self):
        return self.clinic_name

walk_in_clinic/forms.py
from django import forms

from .models import Appointment, Clinic

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['service', 'notes', 'clinic', 'names', 'start_time', 'end_time']
        labels = {'service': 'Service', 'notes': 'Notes', 'clinic': 'Clinic', 'names': 'Name', 'start_time': 'Start time', 'end_time': 'End time'}

class ClinicForm(forms.ModelForm):
    class Meta:
        model = Clinic
        fields = ['dr_name', 'clinic_name', 'location', 'dr_email', 'dr_phonenumber', 'payment_method_available']
        labels = {'dr_name': 'Name', 'clinic_name': 'Clinic Name', 'location': 'Location', 'dr_email': 'Your email', 'dr_phonenumber': 'Your phone number', 'payment_method_available': 'Payment Method for clinic'}

walk_in_clinic/views.py
from django.shortcuts import render, redirect
from .models import Appointment, Clinic
from .forms import AppointmentForm, ClinicForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import Http404

def index(request):
    """The home page for walk-in-clinic."""
    return render(request, 'walk_in_clinic/index.html')


@login_required
@user_passes_test(lambda u: u.groups.filter(name='Doctors').exists())
def appointments_dr(request):
    """Show all appointments."""
    appointments = Appointment.objects.all().order_by('start_time')
    context = {'appointments': appointments}
    return render(request, 'walk_in_clinic/appointments.html', context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='Patients').exists())
def appointments(request):
    """Show all appointments."""
    appointments = Appointment.objects.filter(names=request.user).order_by('start_time')
    context = {'appointments': appointments}
    return render(request, 'walk_in_clinic/appointments.html', context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='Patients').exists())
def appointment(request, appointment_id):
    """Show a single topic"""
    appointment = Appointment.objects.get(id=appointment_id)
    if appointment.names != request.user:
        raise Http404
    context = {'appointment': appointment}
    return render(request, 'walk_in_clinic/appointment.html', context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='Doctors').exists())
def appointment_dr(request, appointment_id):
    """Show a single topic for dr"""
    appointment = Appointment.objects.get(id=appointment_id)
    context = {'appointment': appointment}
    return render(request, 'walk_in_clinic/appointment_dr.html', context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='Patients').exists())
def new_appointment(request):
    """Add a new appointment."""
    if request.method != 'POST':
        form = AppointmentForm()
    else:
        form = AppointmentForm(data=request.POST)
        if form.is_valid():
            new_appointment = form.save(commit=False)
            new_appointment.names = request.user
            new_appointment.save()
            return redirect('walk_in_clinic:appointments')

    context = {'form': form}
    return render(request, 'walk_in_clinic/new_appointment.html', context)


@login_required
#@user_passes_test(lambda u: u.groups.filter(name='Patients').exists())
def edit_appointment(request, appointment_id):
    """edit a appointment."""
    appointment = Appointment.objects.get(id=appointment_id)
    if request.method != 'POST':
        form = AppointmentForm(instance=appointment)
    else:
        form = AppointmentForm(instance=appointment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('walk_in_clinic:appointment', appointment_id=appointment.id)

    context = {'appointment': appointment, 'form': form}
    return render(request, 'walk_in_clinic/edit_appointment.html', context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='Doctors').exists())
def new_clinic(request):
    """Add a new appointment."""
    if request.method != 'POST':
        form = ClinicForm()
    else:
        form = ClinicForm(data=request.POST)
        if form.is_valid():
            new_clinic = form.save(commit=False)
            new_clinic.dr_name = request.user
            new_clinic.save()
            return redirect('walk_in_clinic:index')

    context = {'form': form}
    return render(request, 'walk_in_clinic/new_clinic.html', context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='Patients').exists())
def clinics(request):
    """Show all appointments."""
    clinics = Clinic.objects.all().order_by('clinic_name')
    context = {'clinics': clinics}
    return render(request, 'walk_in_clinic/clinics.html', context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='Doctors').exists())
def clinics_dr(request):
    clinics = Clinic.objects.filter(dr_name=request.user).order_by('clinic_name')
    context = {'clinics': clinics}
    return render(request, 'walk_in_clinic/clinics.html', context)


@login_required
def clinic(request, clinic_id):
    """Show a individual clinic."""
    clinic = Clinic.objects.get(id=clinic_id)
    context = {'clinic': clinic}
    return render(request, 'walk_in_clinic/clinic.html', context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='Doctors').exists())
def edit_clinic(request, clinic_id):
    """edit a clinic."""
    clinic = Clinic.objects.get(id=clinic_id)
    if request.method != 'POST':
        form = ClinicForm(instance=clinic)
    else:
        form = ClinicForm(instance=clinic, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('walk_in_clinic:clinic', clinic_id=clinic.id)

    context = {'clinic': clinic, 'form': form}
    return render(request, 'walk_in_clinic/edit_clinic.html', context)

walk_in_clinic/templates/walk_in_clinic/appointment.html
{% extends 'walk_in_clinic/base.html' %}

{% block content %}

  <p>Appointment: {{ appointment }}</p>

  <p>Name: {{ appointment.names }}</p>

  <p>Clinic: {{ appointment.clinic }}</p>

  <p>start time: {{ appointment.start_time }}</p>

  <p>end time: {{ appointment.end_time }}</p>

  <p>Notes: {{ appointment.notes }}</p>

{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/appointment_dr.html
{% extends "walk_in_clinic/base.html" %}

{% block content %}

  <p>Appointment: {{ appointment }}</p>

  <p>Name: {{ appointment.names }}</p>

  <p>Clinic: {{ appointment.clinic }}</p>

  <p>start time: {{ appointment.start_time }}</p>

  <p>end time: {{ appointment.end_time }}</p>

  <p>Notes: {{ appointment.notes }}</p>

{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/appointments.html
{% extends "walk_in_clinic/base.html" %}

{% block content %}

  <p>Appointments</p>

  {% if user.groups.all.0.name == "Patients" %}
    <ul>
      {% for appointment in appointments %}
        <li>
          <a href={% url 'walk_in_clinic:appointment' appointment.id %}>{{ appointment }}</a>
          <p>
            <a href="{% url 'walk_in_clinic:edit_appointment' appointment.id %}">Edit appointment</a>
          </p>
        </li>
      {% empty %}
        <li>No appointments have been added yet.</li>
      {% endfor %}
    </ul>

    <a href="{% url 'walk_in_clinic:new_appointment' %}">Add a new appointment</a>
  {% else %}
    <ul>
      {% for appointment in appointments %}
        <li>
          <a href={% url 'walk_in_clinic:appointment_dr' appointment.id %}>{{ appointment }}</a>
          <p>
            <a href="{% url 'walk_in_clinic:edit_appointment' appointment.id %}">Edit appointment</a>
          </p>
        </li>
      {% empty %}
        <li>No appointments have been added yet.</li>
      {% endfor %}
    </ul>

    <a href="{% url 'walk_in_clinic:new_appointment' %}">Add a new appointment</a>

  {% endif %}

{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/base.html

{% if user.groups.all.0.name == "Patients" %}
  <p>
    <a href="{% url 'walk_in_clinic:index' %}">Walk In Clinic</a> -
    <a href="{% url 'walk_in_clinic:appointments' %}">Appointments</a> -
    <a href="{% url 'walk_in_clinic:clinics' %}">Clinics</a> -
    {% if user.is_authenticated %}
      Hello, {{ user.username }}.
      <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
      <a href="{% url 'users:register' %}">Register</a> -
      <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
  </p>
{% else %}
  <p>
    <a href="{% url 'walk_in_clinic:index' %}">Walk In Clinic</a> -
    <a href="{% url 'walk_in_clinic:appointments_dr'  %}">Appointments</a> -
    <a href="{% url 'walk_in_clinic:clinics_dr' %}">Clinics</a> -
    {% if user.is_authenticated %}
      Hello, {{ user.username }}.
      <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
      <a href="{% url 'users:register' %}">Register</a> -
      <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
  </p>
{% endif %}

{% block content %}{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/clinic.html
{% extends "walk_in_clinic/base.html" %}

{% block content %}

  <p>Clinic: {{ clinic }}</p>

  <p>Doctor's Name: {{ clinic.dr_name }}</p>

  <p>Location: {{ clinic.location }}</p>

  <p>Payment method: {% if clinic.payment_method_available == "pp" %} Paypal
                     {% elif clinic.payment_method_available == "cc" %} Credit Card
                     {% elif clinic.payment_method_available == "dc" %} Debit Card  
                     {% elif clinic.payment_method_available == "ca" %} Cash
                     {% endif %}</p>

  <p>Doctor's email: {{ clinic.dr_email }}</p>

  <p>Doctor's phone-number: {{ clinic.dr_phonenumber }}</p>

{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/clinics.html
{% extends "walk_in_clinic/base.html" %}

{% block content %}

  {% if user.groups.all.0.name == "Doctors" %}
    <p>Clinics</p>

    <ul>
      {% for clinic in clinics %}
        <li>
          <a href={% url 'walk_in_clinic:clinic' clinic.id %}>{{ clinic }}</a>
        </li>
        <p>
          <a href="{% url 'walk_in_clinic:edit_clinic' clinic.id %}">Edit clinic</a>
      {% empty %}
        <li>No clinics have been added yet.</li>
      {% endfor %}
    </ul>

    <a href="{% url 'walk_in_clinic:new_clinic' %}">Add a new clinc</a>
  {% else %}
    <p>Clinics</p>

    <ul>
      {% for clinic in clinics %}
        <li>
          <a href={% url 'walk_in_clinic:clinic' clinic.id %}>{{ clinic }}</a>
        </li>
      {% empty %}
        <li>No clinics have been added yet.</li>
      {% endfor %}
    </ul>
  {% endif %}

{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/edit_appointment.html
{% extends "walk_in_clinic/base.html" %}

{% block content %}

  <p><a href="{% url 'walk_in_clinic:appointment' appointment.id %}">{{ appointment }}</a></p>

  <p>Edit appointment</p>

  <form action="{% url 'walk_in_clinic:edit_appointment' appointment.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/edit_clinic.html
{% extends "walk_in_clinic/base.html" %}

{% block content %}

  <p><a href="{% url 'walk_in_clinic:clinic' clinic.id %}">{{ clinic }}</a></p>

  <p>Edit clinic</p>

  <form action="{% url 'walk_in_clinic:edit_clinic' clinic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/index.html
{% extends "walk_in_clinic/base.html" %}

{% block content %}

<p>Walk in Clinic can help you find walk in clinics, rate them and much more.</p>

{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/new_appointment.html
{% extends "walk_in_clinic/base.html" %}

{% block content %}
  <p>Add a new appointment:</p>

  <form action="{% url 'walk_in_clinic:new_appointment' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name-"submit">Add appointment</button>
  </form>

{% endblock content %}

walk_in_clinic/templates/walk_in_clinic/new_clinic.html
{% extends "walk_in_clinic/base.html" %}

{% block content %}
  <p>Add a new clinic:</p>

  <form action="{% url 'walk_in_clinic:new_clinic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name-"submit">Add clinic</button>
  </form>

{% endblock content %}